import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from io import BytesIO
from datetime import datetime

# ============================================================
# Page Config
# ============================================================
st.set_page_config(
    page_title="Abacus",
    page_icon="\u25e7",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# Color Palette
# ============================================================
INDIGO = "#3F51B5"
INDIGO_DARK = "#283593"
INDIGO_LIGHT = "#C5CAE9"
INDIGO_BG = "#E8EAF6"

LOGO_URL = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663291964821/QjDLltQWooriJzwW.png"

# ============================================================
# Translations
# ============================================================
TRANSLATIONS = {
    "en": {
        "app_name": "Abacus",
        "tagline": "Financial clarity, simplified.",
        "data_source": "Data Source",
        "upload_file": "Upload File",
        "demo_data": "Demo Data",
        "upload_label": "Upload your financial data",
        "upload_help": "Excel or CSV with columns: Month, Revenue, and expense categories",
        "loaded_rows": "Loaded {n} rows",
        "using_sample": "Using sample data",
        "sidebar_desc": "Upload monthly revenue and expense data. Abacus generates a diagnostic report with actionable insights.",
        "landing_headline": "Stop guessing. Know your numbers.",
        "landing_sub": "We built Abacus because our own spreadsheets were giving us headaches. It's a simple, no-fluff dashboard for your business.",
        "landing_hint": "Upload an Excel file or just try the Demo Data to see how it works.",
        "how_title": "How it works (it's simple)",
        "how_1": "Drop in your monthly P&L spreadsheet.",
        "how_2": "We instantly figure out your margins, trends, and where the money is going.",
        "how_3": "You get a clean report with straightforward tips.",
        "footer": "Built for founders, by founders.",
        "report_title": "Financial Diagnostic Report",
        "revenue": "Revenue",
        "expenses": "Expenses",
        "net_profit": "Net Profit",
        "net_margin": "Net Margin",
        "growth": "Growth",
        "health_check": "Health Check",
        "gross_margin": "Gross Margin",
        "revenue_growth": "Revenue Growth",
        "profitable_months": "Profitable Months",
        "healthy": "Healthy",
        "caution": "Caution",
        "at_risk": "At Risk",
        "tab_trends": "Trends",
        "tab_costs": "Cost Structure",
        "tab_data": "Data",
        "tab_insights": "Insights",
        "tab_about": "About",
        "rev_vs_profit": "Revenue vs Net Profit",
        "monthly_margin": "Monthly Profit Margin",
        "month": "Month",
        "amount": "Amount",
        "profit_margin_label": "Profit Margin",
        "category": "Category",
        "share": "Share",
        "download": "Download Full Report",
        "download_pdf": "Download PDF Report",
        "pdf_title": "Abacus Financial Diagnostic Report",
        "pdf_generated": "Report generated by Abacus",
        "pdf_summary": "Executive Summary",
        "pdf_health": "Health Check",
        "pdf_cost_title": "Cost Breakdown",
        "pdf_insights_title": "Key Insights",
        "insights_disclaimer": "These insights are generated based on standard financial benchmarks. They are not a substitute for professional financial advice.",
        "best_month": "Best Month",
        "worst_month": "Worst Month",
        "avg_profit": "Avg Monthly Profit",
        "profit_word": "profit",
        "about_problem_title": "Our Story",
        "about_problem": "I used to spend hours every Sunday night staring at a giant Excel file, trying to figure out if we were actually making money. It was a mess of rows and formulas, and I never felt confident I knew what was really going on. Are we growing? Is our margin getting better or worse? Where is all the cash going? Answering these basic questions felt way too hard.",
        "about_solution_title": "A Dashboard, Not Another Spreadsheet",
        "about_solution": "Abacus is the tool I wish I had. You just upload your numbers, and it gives you the handful of metrics that actually matter, in plain English. No accounting jargon, no complicated setup. It's not about replacing your accountant; it's about giving you a quick, honest look at your business's health, anytime you want.",
        "about_principles_title": "What We Believe",
        "about_principle_1": "Your own data is your best consultant. We just help you listen to it.",
        "about_principle_2": "You shouldn't need an MBA to understand your own business.",
        "about_principle_3": "A good tool gives you answers, not more questions.",
        "about_built": "Built by Abacus Labs",
        # Insights
        "insight_strong_nm": "Your net margin is looking great. You're keeping a healthy chunk of every dollar that comes in. Nice work.",
        "insight_moderate_nm": "Your net margin is okay, but could be better. Time to look at your big-ticket expenses and see where you can trim.",
        "insight_thin_nm": "Your net margin is razor-thin. Your costs are eating up almost all your revenue. It's time for a serious look at your spending.",
        "insight_strong_gm": "A healthy gross margin like this means your core business is profitable. You're pricing your products well.",
        "insight_weak_gm": "Your gross margin is on the low side. Are your production costs too high? Or could you be charging more?",
        "insight_strong_growth": "You're growing fast! That's great, but make sure you can actually handle more orders before you spend more on ads.",
        "insight_steady_growth": "Growth is steady. What's the next gear? Time to think about a new marketing channel or product idea.",
        "insight_decline": "Revenue is heading down. Let's figure out why. Are customers leaving? Or is it just a slow season?",
        "insight_top_cost": "Watch out: {name} makes up {pct:.0f}% of your total costs. If that price goes up, it's going to hurt.",
        "insight_seasonality": "You make most of your money around {best}. Your slow month is {worst}. Use this rhythm to your advantage when planning cash flow.",
    },
    "zh": {
        "app_name": "Abacus",
        "tagline": "\u8d22\u52a1\u6d1e\u5bdf\uff0c\u5316\u7e41\u4e3a\u7b80",
        "data_source": "\u6570\u636e\u6765\u6e90",
        "upload_file": "\u4e0a\u4f20\u6587\u4ef6",
        "demo_data": "\u6f14\u793a\u6570\u636e",
        "upload_label": "\u4e0a\u4f20\u4f60\u7684\u8d22\u52a1\u6570\u636e",
        "upload_help": "Excel \u6216 CSV \u6587\u4ef6\uff0c\u5305\u542b\u6708\u4efd\u3001\u8425\u6536\u548c\u5404\u9879\u652f\u51fa",
        "loaded_rows": "\u5df2\u52a0\u8f7d {n} \u884c\u6570\u636e",
        "using_sample": "\u6b63\u5728\u4f7f\u7528\u6f14\u793a\u6570\u636e",
        "sidebar_desc": "\u4e0a\u4f20\u6708\u5ea6\u8425\u6536\u4e0e\u652f\u51fa\u6570\u636e\uff0cAbacus \u4f1a\u81ea\u52a8\u751f\u6210\u8bca\u65ad\u62a5\u544a\u548c\u53ef\u6267\u884c\u7684\u5efa\u8bae",
        "landing_headline": "别再猜了。看数字。",
        "landing_sub": "我们做 Abacus 是因为我们自己的表格也曾让我们头疼。这是一个给你的生意做的、简单、没废话的仪表盘。",
        "landing_hint": "上传一个 Excel 文件，或者直接试试演示数据，看看它怎么用。",
        "how_title": "三步搞定",
        "how_1": "拖入你每月的 P&L 表格。",
        "how_2": "我们马上算出你的利润、趋势，以及钱花哪儿了。",
        "how_3": "你会得到一份干净的报告和一些直接的建议。",
        "footer": "创始人致创始人",
        "report_title": "\u8d22\u52a1\u8bca\u65ad\u62a5\u544a",
        "revenue": "\u8425\u6536",
        "expenses": "\u652f\u51fa",
        "net_profit": "\u51c0\u5229\u6da6",
        "net_margin": "\u51c0\u5229\u6da6\u7387",
        "growth": "\u589e\u957f\u7387",
        "health_check": "\u5065\u5eb7\u68c0\u67e5",
        "gross_margin": "\u6bdb\u5229\u7387",
        "revenue_growth": "\u8425\u6536\u589e\u957f",
        "profitable_months": "\u76c8\u5229\u6708\u4efd",
        "healthy": "\u5065\u5eb7",
        "caution": "\u8b66\u544a",
        "at_risk": "\u9ad8\u98ce\u9669",
        "tab_trends": "\u8d8b\u52bf",
        "tab_costs": "\u6210\u672c\u7ed3\u6784",
        "tab_data": "\u6570\u636e",
        "tab_insights": "\u5206\u6790\u5efa\u8bae",
        "tab_about": "\u5173\u4e8e",
        "rev_vs_profit": "\u8425\u6536 vs \u51c0\u5229\u6da6",
        "monthly_margin": "\u6708\u5ea6\u5229\u6da6\u7387",
        "month": "\u6708\u4efd",
        "amount": "\u91d1\u989d",
        "profit_margin_label": "\u5229\u6da6\u7387",
        "category": "\u7c7b\u522b",
        "share": "\u5360\u6bd4",
        "download": "\u4e0b\u8f7d\u5b8c\u6574\u62a5\u544a",
        "download_pdf": "\u4e0b\u8f7d PDF \u62a5\u544a",
        "pdf_title": "Abacus \u8d22\u52a1\u8bca\u65ad\u62a5\u544a",
        "pdf_generated": "\u62a5\u544a\u7531 Abacus \u751f\u6210",
        "pdf_summary": "\u6982\u8981",
        "pdf_health": "\u5065\u5eb7\u68c0\u67e5",
        "pdf_cost_title": "\u6210\u672c\u5206\u89e3",
        "pdf_insights_title": "\u5173\u952e\u5efa\u8bae",
        "insights_disclaimer": "\u8fd9\u4e9b\u5efa\u8bae\u57fa\u4e8e\u6807\u51c6\u8d22\u52a1\u57fa\u51c6\u751f\u6210\uff0c\u4e0d\u80fd\u66ff\u4ee3\u4e13\u4e1a\u8d22\u52a1\u5efa\u8bae",
        "best_month": "\u6700\u4f73\u6708\u4efd",
        "worst_month": "\u6700\u5dee\u6708\u4efd",
        "avg_profit": "\u6708\u5747\u5229\u6da6",
        "profit_word": "\u5229\u6da6",
        "about_problem_title": "我们的故事",
        "about_problem": "我以前每个周日晚上都要花好几个小时盯着一个巨大的 Excel 文件，就为了搞清楚我们到底赚没赚钱。表格里全是行和公式，乱七八糟，我从来没有信心说我真正了解业务的状况。我们在增长吗？利润率是变好了还是变差了？钱都花到哪里去了？回答这些基本问题感觉太难了。",
        "about_solution_title": "一个仪表盘，而不是又一张表格",
        "about_solution": "Abacus 就是我当年希望拥有的工具。你上传数字，它用大白话告诉你那几个真正重要的指标。没有会计术语，没有复杂的设置。它不是要取代你的会计，而是让你随时能快速、真实地看一眼你的业务健康状况。",
        "about_principles_title": "我们信奉",
        "about_principle_1": "你自己的数据就是你最好的顾问。我们只是帮你听懂它。",
        "about_principle_2": "你不应该需要一个 MBA 学位才能看懂自己的生意。",
        "about_principle_3": "一个好工具是给你答案，而不是更多的问题。",
        "about_built": "\u7531 Abacus Labs \u6784\u5efa",
        "insight_strong_nm": "你的净利润率看起来很棒。每一块钱的收入你都留下了可观的一部分。干得漂亮。",
        "insight_moderate_nm": "你的净利润率还行，但可以更好。是时候看看你的大头支出，想想哪里能省点了。",
        "insight_thin_nm": "你的净利润率薄如纸。成本几乎吃掉了你所有的收入。是时候严肃审视一下你的开销了。",
        "insight_strong_gm": "这么健康的毛利率意味着你的核心业务是赚钱的。你的产品定价做得不错。",
        "insight_weak_gm": "你的毛利率偏低。是生产成本太高了？还是说你可以卖得更贵一点？",
        "insight_strong_growth": "你增长得很快！这很好，但在花更多钱打广告之前，先确保你能处理得了更多的订单。",
        "insight_steady_growth": "增长很稳。下一个档位是什么？是时候考虑新的营销渠道或产品点子了。",
        "insight_decline": "收入在下滑。我们得搞清楚为什么。是客户流失了？还是只是淡季？",
        "insight_top_cost": "注意：{name} 占了你总成本的 {pct:.0f}%。如果这个价格上涨，你会很受伤。",
        "insight_seasonality": "你在 {best} 赚得最多，在 {worst} 是你的淡季。利用这个节奏来规划现金流，你会更从容。",
    },
    "es": {
        "app_name": "Abacus",
        "tagline": "Claridad financiera, simplificada.",
        "data_source": "Fuente de datos",
        "upload_file": "Subir archivo",
        "demo_data": "Datos de prueba",
        "upload_label": "Sube tus datos financieros",
        "upload_help": "Excel o CSV con columnas: Mes, Ingresos y categor\u00edas de gastos",
        "loaded_rows": "{n} filas cargadas",
        "using_sample": "Usando datos de prueba",
        "sidebar_desc": "Sube datos mensuales de ingresos y gastos. Abacus genera un informe de diagn\u00f3stico con recomendaciones pr\u00e1cticas.",
        "landing_headline": "Deja de adivinar. Conoce tus números.",
        "landing_sub": "Creamos Abacus porque nuestras propias hojas de cálculo nos daban dolores de cabeza. Es un panel de control simple y directo para tu negocio.",
        "landing_hint": "Sube un archivo de Excel o simplemente prueba los Datos de Demostración para ver cómo funciona.",
        "how_title": "Así de fácil",
        "how_1": "Arrastra tu hoja de pérdidas y ganancias mensual.",
        "how_2": "Calculamos al instante tus márgenes, tendencias y a dónde se va el dinero.",
        "how_3": "Obtienes un informe limpio con consejos claros.",
        "footer": "De fundadores, para fundadores.",
        "report_title": "Informe de Diagn\u00f3stico Financiero",
        "revenue": "Ingresos",
        "expenses": "Gastos",
        "net_profit": "Beneficio Neto",
        "net_margin": "Margen Neto",
        "growth": "Crecimiento",
        "health_check": "Chequeo de Salud",
        "gross_margin": "Margen Bruto",
        "revenue_growth": "Crecimiento de Ingresos",
        "profitable_months": "Meses Rentables",
        "healthy": "Saludable",
        "caution": "Precauci\u00f3n",
        "at_risk": "En Riesgo",
        "tab_trends": "Tendencias",
        "tab_costs": "Estructura de Costos",
        "tab_data": "Datos",
        "tab_insights": "An\u00e1lisis",
        "tab_about": "Acerca de",
        "rev_vs_profit": "Ingresos vs Beneficio Neto",
        "monthly_margin": "Margen de Beneficio Mensual",
        "month": "Mes",
        "amount": "Monto",
        "profit_margin_label": "Margen de Beneficio",
        "category": "Categor\u00eda",
        "share": "Proporci\u00f3n",
        "download": "Descargar Informe Completo",
        "download_pdf": "Descargar Informe PDF",
        "pdf_title": "Informe de Diagn\u00f3stico Financiero Abacus",
        "pdf_generated": "Informe generado por Abacus",
        "pdf_summary": "Resumen Ejecutivo",
        "pdf_health": "Chequeo de Salud",
        "pdf_cost_title": "Desglose de Costos",
        "pdf_insights_title": "Recomendaciones Clave",
        "insights_disclaimer": "Estas recomendaciones se generan en base a est\u00e1ndares financieros. No sustituyen el asesoramiento financiero profesional.",
        "best_month": "Mejor Mes",
        "worst_month": "Peor Mes",
        "avg_profit": "Beneficio Mensual Promedio",
        "profit_word": "beneficio",
        "about_problem_title": "Nuestra Historia",
        "about_problem": "Solía pasar horas cada domingo por la noche mirando un archivo de Excel gigante, tratando de averiguar si realmente estábamos ganando dinero. Era un desastre de filas y fórmulas, y nunca me sentí seguro de saber lo que realmente estaba pasando. ¿Estamos creciendo? ¿Nuestro margen está mejorando o empeorando? ¿A dónde se va todo el efectivo? Responder a estas preguntas básicas parecía demasiado difícil.",
        "about_solution_title": "Un Panel de Control, No Otra Hoja de Cálculo",
        "about_solution": "Abacus es la herramienta que desearía haber tenido. Simplemente subes tus números y te da las pocas métricas que realmente importan, en un lenguaje sencillo. Sin jerga contable, sin configuraciones complicadas. No se trata de reemplazar a tu contador; se trata de darte una visión rápida y honesta de la salud de tu negocio, cuando quieras.",
        "about_principles_title": "En lo que creemos",
        "about_principle_1": "Tus propios datos son tu mejor consultor. Nosotros solo te ayudamos a escucharlos.",
        "about_principle_2": "No deberías necesitar un MBA para entender tu propio negocio.",
        "about_principle_3": "Una buena herramienta te da respuestas, no más preguntas.",
        "about_built": "Desarrollado por Abacus Labs",
        "insight_strong_nm": "Tu margen neto se ve genial. Estás conservando una buena parte de cada dólar que entra. Buen trabajo.",
        "insight_moderate_nm": "Tu margen neto está bien, pero podría ser mejor. Es hora de mirar tus gastos más grandes y ver dónde puedes recortar.",
        "insight_thin_nm": "Tu margen neto es muy ajustado. Tus costos se están comiendo casi todos tus ingresos. Es hora de revisar seriamente tus gastos.",
        "insight_strong_gm": "Un margen bruto saludable como este significa que tu negocio principal es rentable. Estás fijando bien los precios de tus productos.",
        "insight_weak_gm": "Tu margen bruto es un poco bajo. ¿Son tus costos de producción demasiado altos? ¿O podrías estar cobrando más?",
        "insight_strong_growth": "¡Estás creciendo rápido! Eso es genial, pero asegúrate de que realmente puedes manejar más pedidos antes de gastar más en anuncios.",
        "insight_steady_growth": "El crecimiento es estable. ¿Cuál es el siguiente paso? Es hora de pensar en un nuevo canal de marketing o una idea de producto.",
        "insight_decline": "Los ingresos están bajando. Averigüemos por qué. ¿Se están yendo los clientes? ¿O es solo una temporada baja?",
        "insight_top_cost": "Cuidado: {name} representa el {pct:.0f}% de tus costos totales. Si ese precio sube, te va a doler.",
        "insight_seasonality": "Ganas la mayor parte de tu dinero alrededor de {best}. Tu mes más flojo es {worst}. Usa este ritmo a tu favor al planificar el flujo de caja.",
    }
}


# ============================================================
# Custom CSS
# ============================================================
st.markdown(f"""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Source+Serif+4:wght@400;600&display=swap');

    .stApp {{
        background-color: #ffffff;
        font-family: 'Inter', sans-serif;
    }}

    section[data-testid="stSidebar"] {{
        background-color: #f8f9fc;
        border-right: 1px solid #e8eaf0;
    }}
    section[data-testid="stSidebar"] .stMarkdown p,
    section[data-testid="stSidebar"] .stMarkdown li,
    section[data-testid="stSidebar"] .stMarkdown label {{
        color: #555;
        font-size: 0.88rem;
    }}
    section[data-testid="stSidebar"] h1,
    section[data-testid="stSidebar"] h2,
    section[data-testid="stSidebar"] h3 {{
        color: #222;
    }}

    h1 {{
        font-family: 'Source Serif 4', serif !important;
        font-weight: 600 !important;
        color: #1a1a2e !important;
        letter-spacing: -0.02em;
    }}
    h2, h3 {{
        font-family: 'Inter', sans-serif !important;
        font-weight: 500 !important;
        color: #222 !important;
    }}

    div[data-testid="stMetric"] {{
        background-color: #ffffff;
        border: 1px solid #e0e3eb;
        border-radius: 10px;
        padding: 18px 22px;
        box-shadow: 0 1px 3px rgba(63,81,181,0.04);
    }}
    div[data-testid="stMetric"] label {{
        color: #7986CB !important;
        font-size: 0.75rem !important;
        text-transform: uppercase;
        letter-spacing: 0.07em;
    }}
    div[data-testid="stMetric"] div[data-testid="stMetricValue"] {{
        color: #1a1a2e !important;
        font-weight: 600 !important;
    }}

    .stTabs [data-baseweb="tab-list"] {{
        gap: 0px;
        border-bottom: 1px solid #e0e3eb;
    }}
    .stTabs [data-baseweb="tab"] {{
        font-family: 'Inter', sans-serif;
        font-size: 0.85rem;
        font-weight: 500;
        color: #9e9e9e;
        padding: 10px 24px;
        border-bottom: 2px solid transparent;
    }}
    .stTabs [aria-selected="true"] {{
        color: {INDIGO} !important;
        border-bottom: 2px solid {INDIGO} !important;
    }}

    hr {{
        border: none;
        border-top: 1px solid #e8eaf0;
        margin: 2rem 0;
    }}

    .footer-text {{
        text-align: center;
        color: #b0b0b0;
        font-size: 0.75rem;
        padding: 2rem 0 1rem 0;
        letter-spacing: 0.04em;
    }}

    #MainMenu {{visibility: hidden;}}
    footer {{visibility: hidden;}}

    .stButton > button {{
        background-color: {INDIGO};
        color: #ffffff;
        border: none;
        border-radius: 8px;
        font-weight: 500;
        font-size: 0.85rem;
        padding: 0.5rem 1.5rem;
        letter-spacing: 0.02em;
    }}
    .stButton > button:hover {{
        background-color: {INDIGO_DARK};
        color: #ffffff;
    }}

    .stDataFrame {{
        border: 1px solid #e0e3eb;
        border-radius: 10px;
    }}

    .stDownloadButton > button {{
        background-color: #ffffff;
        color: {INDIGO};
        border: 1px solid {INDIGO};
        border-radius: 8px;
        font-weight: 500;
    }}
    .stDownloadButton > button:hover {{
        background-color: {INDIGO_BG};
        color: {INDIGO_DARK};
    }}
</style>
""", unsafe_allow_html=True)


# ============================================================
# Helper Functions
# ============================================================

def traffic_light(value, good_threshold, bad_threshold, higher_is_better=True):
    if higher_is_better:
        if value >= good_threshold:
            return t["healthy"], "#2E7D32"
        elif value >= bad_threshold:
            return t["caution"], "#F57F17"
        else:
            return t["at_risk"], "#C62828"
    else:
        if value <= good_threshold:
            return t["healthy"], "#2E7D32"
        elif value <= bad_threshold:
            return t["caution"], "#F57F17"
        else:
            return t["at_risk"], "#C62828"


def generate_insights(results, t):
    insights = []
    nm = results['net_margin']
    gm = results['gross_margin']
    growth = results['revenue_growth']

    if nm > 15:
        insights.append(t["insight_strong_nm"])
    elif nm > 5:
        insights.append(t["insight_moderate_nm"])
    else:
        insights.append(t["insight_thin_nm"])

    if gm > 60:
        insights.append(t["insight_strong_gm"])
    elif gm < 40:
        insights.append(t["insight_weak_gm"])

    if growth > 30:
        insights.append(t["insight_strong_growth"])
    elif growth > 0:
        insights.append(t["insight_steady_growth"])
    else:
        insights.append(t["insight_decline"])

    sorted_costs = sorted(results['cost_breakdown'].items(), key=lambda x: x[1], reverse=True)
    top_cost = sorted_costs[0]
    pct = (top_cost[1] / results['total_expenses']) * 100
    if pct > 35:
        insights.append(t["insight_top_cost"].format(name=top_cost[0], pct=pct))

    best = results['best_month']
    worst = results['worst_month']
    insights.append(t["insight_seasonality"].format(best=best, worst=worst))

    return insights


def generate_pdf(results, t, insights):
    """Generate a professional PDF diagnostic report using HTML + WeasyPrint."""
    import weasyprint

    # Health check logic
    checks = [
        (t["gross_margin"], results['gross_margin'], 50, 30, True),
        (t["net_margin"], results['net_margin'], 10, 5, True),
        (t.get("revenue_growth", "REVENUE GROWTH"), results['revenue_growth'], 20, 0, True),
        (t["profitable_months"], (results['months_profitable']/results['total_months'])*100, 80, 50, True),
    ]

    health_rows = ""
    for label, val, good, bad, higher in checks:
        if higher:
            if val >= good:
                status, color = t["healthy"], "#2E7D32"
            elif val >= bad:
                status, color = t["caution"], "#F57F17"
            else:
                status, color = t["at_risk"], "#C62828"
        else:
            if val <= good:
                status, color = t["healthy"], "#2E7D32"
            elif val <= bad:
                status, color = t["caution"], "#F57F17"
            else:
                status, color = t["at_risk"], "#C62828"
        health_rows += f'<tr><td>{label}</td><td style="color:{color};font-weight:600;">{status}</td><td class="num">{val:.1f}%</td></tr>\n'

    # Cost breakdown
    sorted_costs = sorted(results['cost_breakdown'].items(), key=lambda x: x[1], reverse=True)
    total_exp = results['total_expenses']
    cost_rows = ""
    for name, val in sorted_costs:
        pct = (val / total_exp) * 100
        cost_rows += f'<tr><td>{name}</td><td class="num">${val:,.0f}</td><td class="num">{pct:.1f}%</td></tr>\n'

    # Insights
    insight_items = ""
    for i, ins in enumerate(insights, 1):
        insight_items += f'<div class="insight"><span class="insight-num">{i}.</span> {ins}</div>\n'

    date_str = datetime.now().strftime("%Y-%m-%d")

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Noto Sans CJK SC', 'Noto Sans SC', 'Noto Sans', 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; font-size: 10px; padding: 40px; }}
.header {{ border-bottom: 2px solid #E8EAF0; padding-bottom: 12px; margin-bottom: 24px; }}
.header h1 {{ font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 2px; }}
.header .subtitle {{ font-size: 10px; color: #7986CB; }}
.section-title {{ font-size: 14px; font-weight: 700; color: #3F51B5; margin: 20px 0 10px 0; }}
.metrics {{ display: flex; justify-content: space-between; margin-bottom: 20px; }}
.metric {{ text-align: center; flex: 1; }}
.metric .label {{ font-size: 8px; color: #7986CB; text-transform: uppercase; letter-spacing: 0.5px; }}
.metric .value {{ font-size: 16px; font-weight: 700; color: #1a1a2e; margin-top: 2px; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 8px; }}
th {{ background: #F8F9FC; color: #505050; font-weight: 600; text-align: left; padding: 6px 8px; font-size: 9px; }}
td {{ padding: 5px 8px; font-size: 9px; border-bottom: 1px solid #F0F0F0; }}
.num {{ text-align: right; }}
.insight {{ margin-bottom: 8px; line-height: 1.5; font-size: 9px; color: #333; }}
.insight-num {{ color: #3F51B5; font-weight: 700; }}
.summary {{ display: flex; flex-wrap: wrap; border-top: 2px solid #E8EAF0; padding-top: 12px; margin-top: 16px; }}
.summary-item {{ width: 25%; margin-bottom: 8px; }}
.summary-item .label {{ font-size: 8px; color: #7986CB; }}
.summary-item .value {{ font-size: 11px; font-weight: 700; color: #1a1a2e; }}
.footer {{ text-align: center; color: #B0B0B0; font-size: 7px; margin-top: 30px; }}
</style>
</head>
<body>
<div class="header">
    <h1>Abacus</h1>
    <div class="subtitle">{t["pdf_title"]}</div>
</div>

<div class="section-title">{t["pdf_summary"]}</div>
<div class="metrics">
    <div class="metric"><div class="label">{t["revenue"]}</div><div class="value">${results['total_revenue']:,.0f}</div></div>
    <div class="metric"><div class="label">{t["expenses"]}</div><div class="value">${results['total_expenses']:,.0f}</div></div>
    <div class="metric"><div class="label">{t["net_profit"]}</div><div class="value">${results['total_profit']:,.0f}</div></div>
    <div class="metric"><div class="label">{t["net_margin"]}</div><div class="value">{results['net_margin']:.1f}%</div></div>
    <div class="metric"><div class="label">{t["growth"]}</div><div class="value">{results['revenue_growth']:.1f}%</div></div>
</div>

<div class="section-title">{t["pdf_health"]}</div>
<table>
    {health_rows}
</table>

<div class="section-title">{t["pdf_cost_title"]}</div>
<table>
    <tr><th>{t["category"]}</th><th class="num">{t["amount"]}</th><th class="num">{t["share"]}</th></tr>
    {cost_rows}
</table>

<div class="section-title">{t["pdf_insights_title"]}</div>
{insight_items}

<div class="summary">
    <div class="summary-item"><div class="label">{t["best_month"]}</div><div class="value">{results['best_month']} (${results['best_profit']:,.0f})</div></div>
    <div class="summary-item"><div class="label">{t["worst_month"]}</div><div class="value">{results['worst_month']} (${results['worst_profit']:,.0f})</div></div>
    <div class="summary-item"><div class="label">{t["avg_profit"]}</div><div class="value">${results['avg_monthly_profit']:,.0f}</div></div>
    <div class="summary-item"><div class="label">{t["gross_margin"]}</div><div class="value">{results['gross_margin']:.1f}%</div></div>
</div>

<div class="footer">{t["pdf_generated"]}  |  {date_str}</div>
</body>
</html>"""

    pdf_bytes = weasyprint.HTML(string=html).write_pdf()
    buf = BytesIO(pdf_bytes)
    return buf


def calculate_metrics(df):
    rev_col = None
    for col in df.columns:
        if any(k in col.lower() for k in ['revenue', 'sales', 'income']):
            rev_col = col
            break
    if rev_col is None:
        numeric_cols = df.select_dtypes(include='number').columns.tolist()
        if numeric_cols:
            rev_col = numeric_cols[0]

    month_col = None
    for col in df.columns:
        if 'month' in col.lower():
            month_col = col
            break
    if month_col is None:
        non_numeric = df.select_dtypes(exclude='number').columns.tolist()
        month_col = non_numeric[0] if non_numeric else None

    cogs_col = None
    for col in df.columns:
        if any(k in col.upper() for k in ['COGS', 'COST_OF_GOODS', 'COST OF GOODS', 'DIRECT_COST']):
            cogs_col = col
            break

    numeric_cols = df.select_dtypes(include='number').columns.tolist()
    expense_cols = [c for c in numeric_cols if c != rev_col]

    df['Total_Expenses'] = df[expense_cols].sum(axis=1)
    df['Net_Profit'] = df[rev_col] - df['Total_Expenses']
    df['Profit_Margin'] = (df['Net_Profit'] / df[rev_col] * 100).round(1)

    total_rev = df[rev_col].sum()
    total_exp = df['Total_Expenses'].sum()
    total_profit = total_rev - total_exp

    if cogs_col:
        gross_margin = ((total_rev - df[cogs_col].sum()) / total_rev) * 100
    else:
        gross_margin = ((total_rev - total_exp) / total_rev) * 100

    net_margin = (total_profit / total_rev) * 100
    revenue_growth = ((df[rev_col].iloc[-1] - df[rev_col].iloc[0]) / df[rev_col].iloc[0]) * 100 if df[rev_col].iloc[0] != 0 else 0

    best_idx = df['Net_Profit'].idxmax()
    worst_idx = df['Net_Profit'].idxmin()

    cost_breakdown = {}
    for col in expense_cols:
        cost_breakdown[col] = df[col].sum()

    avg_monthly_profit = df['Net_Profit'].mean()
    months_profitable = (df['Net_Profit'] > 0).sum()

    return {
        'monthly_data': df,
        'rev_col': rev_col,
        'month_col': month_col,
        'total_revenue': total_rev,
        'total_expenses': total_exp,
        'total_profit': total_profit,
        'gross_margin': gross_margin,
        'net_margin': net_margin,
        'revenue_growth': revenue_growth,
        'best_month': df.loc[best_idx, month_col] if month_col else f"Row {best_idx+1}",
        'best_profit': df.loc[best_idx, 'Net_Profit'],
        'worst_month': df.loc[worst_idx, month_col] if month_col else f"Row {worst_idx+1}",
        'worst_profit': df.loc[worst_idx, 'Net_Profit'],
        'cost_breakdown': cost_breakdown,
        'avg_monthly_profit': avg_monthly_profit,
        'months_profitable': months_profitable,
        'total_months': len(df)
    }


def create_demo_data():
    data = {
        'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        'Revenue': [12000, 11500, 13200, 14800, 16500, 18200,
                    19000, 18500, 15800, 14200, 13500, 17800],
        'COGS': [4800, 4600, 5280, 5920, 6600, 7280,
                 7600, 7400, 6320, 5680, 5400, 7120],
        'Rent': [3000, 3000, 3000, 3000, 3000, 3000,
                 3000, 3000, 3000, 3000, 3000, 3000],
        'Wages': [4000, 4000, 4000, 4500, 5000, 5500,
                  5500, 5500, 4500, 4000, 4000, 5000],
        'Utilities': [500, 480, 520, 550, 600, 700,
                      750, 720, 600, 550, 500, 580],
        'Marketing': [200, 150, 300, 500, 800, 1000,
                      800, 600, 400, 300, 200, 500],
        'Other': [300, 250, 280, 320, 350, 400,
                  380, 360, 300, 280, 250, 350]
    }
    return pd.DataFrame(data)


# ============================================================
# Sidebar
# ============================================================

with st.sidebar:
    st.markdown(
        f'<div style="display:flex; align-items:center; gap:12px; padding:8px 0 16px 0;">'
        f'<img src="{LOGO_URL}" style="width:40px; height:40px; border-radius:10px;">'
        f'<span style="font-family:Source Serif 4,serif; font-size:1.3rem; font-weight:600; color:#1a1a2e;">Abacus</span>'
        f'</div>',
        unsafe_allow_html=True
    )

    # Language selector
    lang_choice = st.selectbox(
        "Language",
        ["English", "\u4e2d\u6587", "Espa\u00f1ol"],
        label_visibility="collapsed"
    )
    lang_map = {"English": "en", "\u4e2d\u6587": "zh", "Espa\u00f1ol": "es"}
    t = TRANSLATIONS[lang_map[lang_choice]]

    st.markdown(
        f'<p style="color:#888; font-size:0.8rem; margin-top:-8px;">{t["tagline"]}</p>',
        unsafe_allow_html=True
    )
    st.markdown("---")

    st.markdown(f'##### {t["data_source"]}')
    data_source = st.radio(
        "Choose input method",
        [t["upload_file"], t["demo_data"]],
        label_visibility="collapsed"
    )

    df = None

    if data_source == t["upload_file"]:
        uploaded_file = st.file_uploader(
            t["upload_label"],
            type=['xlsx', 'xls', 'csv'],
            help=t["upload_help"]
        )
        if uploaded_file:
            try:
                if uploaded_file.name.endswith('.csv'):
                    df = pd.read_csv(uploaded_file)
                else:
                    df = pd.read_excel(uploaded_file)
                st.success(t["loaded_rows"].format(n=len(df)))
            except Exception as e:
                st.error(f"Error: {e}")
    else:
        df = create_demo_data()
        st.markdown(
            f'<p style="color:{INDIGO}; font-size:0.82rem;">{t["using_sample"]}</p>',
            unsafe_allow_html=True
        )

    st.markdown("---")
    st.markdown(
        f'<p style="color:#999; font-size:0.72rem; line-height:1.5;">'
        f'{t["sidebar_desc"]}'
        f'</p>',
        unsafe_allow_html=True
    )


# ============================================================
# Main Content
# ============================================================

if df is None:
    st.markdown("")
    st.markdown("")

    col_l, col_c, col_r = st.columns([1, 3, 1])
    with col_c:
        st.markdown(
            f'<div style="display:flex; align-items:center; gap:16px; margin-bottom:8px;">'
            f'<img src="{LOGO_URL}" style="width:52px; height:52px; border-radius:12px;">'
            f'<h1 style="margin:0; font-size:2.4rem;">Abacus</h1>'
            f'</div>',
            unsafe_allow_html=True
        )
        st.markdown(
            f'<p style="color:#666; font-size:1.1rem; line-height:1.7; max-width:520px;">'
            f'{t["landing_headline"]}'
            f'</p>',
            unsafe_allow_html=True
        )
        st.markdown(
            f'<p style="color:#999; font-size:0.95rem; max-width:520px;">'
            f'{t["landing_sub"]}'
            f'</p>',
            unsafe_allow_html=True
        )
        st.markdown("")
        st.markdown(
            f'<p style="color:#999; font-size:0.85rem;">'
            f'{t["landing_hint"]}'
            f'</p>',
            unsafe_allow_html=True
        )

        st.markdown("---")

        st.markdown(f'##### {t["how_title"]}')
        st.markdown(
            f'<p style="color:#555; font-size:0.9rem; line-height:1.8;">'
            f'<strong style="color:{INDIGO};">1.</strong> {t["how_1"]}<br>'
            f'<strong style="color:{INDIGO};">2.</strong> {t["how_2"]}<br>'
            f'<strong style="color:{INDIGO};">3.</strong> {t["how_3"]}'
            f'</p>',
            unsafe_allow_html=True
        )

        st.markdown("---")
        st.markdown(
            f'<p class="footer-text">{t["footer"]}</p>',
            unsafe_allow_html=True
        )

else:
    results = calculate_metrics(df)
    m = results['monthly_data']
    rev_col = results['rev_col']
    month_col = results['month_col']

    # Header
    st.markdown(
        f'<div style="display:flex; align-items:center; gap:14px; margin-bottom:4px;">'
        f'<img src="{LOGO_URL}" style="width:36px; height:36px; border-radius:8px;">'
        f'<h1 style="margin:0; font-size:1.8rem;">Abacus</h1>'
        f'</div>',
        unsafe_allow_html=True
    )
    st.markdown(
        f'<p style="color:#7986CB; font-size:0.85rem; margin-top:-4px;">{t["report_title"]}</p>',
        unsafe_allow_html=True
    )
    st.markdown("---")

    # ---- Key Metrics ----
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric(t["revenue"], f"${results['total_revenue']:,.0f}")
    c2.metric(t["expenses"], f"${results['total_expenses']:,.0f}")
    c3.metric(t["net_profit"], f"${results['total_profit']:,.0f}")
    c4.metric(t["net_margin"], f"{results['net_margin']:.1f}%")
    c5.metric(t["growth"], f"{results['revenue_growth']:.1f}%")

    st.markdown("")

    # ---- Health Check ----
    st.markdown(f'##### {t["health_check"]}')
    h1, h2, h3, h4 = st.columns(4)

    checks = [
        (t["gross_margin"], results['gross_margin'], 50, 30, True),
        (t["net_margin"], results['net_margin'], 10, 5, True),
        (t["revenue_growth"], results['revenue_growth'], 20, 0, True),
        (t["profitable_months"], (results['months_profitable']/results['total_months'])*100, 80, 50, True),
    ]

    for col, (label, val, good, bad, higher) in zip([h1, h2, h3, h4], checks):
        status, color = traffic_light(val, good, bad, higher)
        col.markdown(
            f'<div style="background:#ffffff; border:1px solid #e0e3eb; border-radius:10px; padding:16px 20px; box-shadow:0 1px 3px rgba(63,81,181,0.04);">'
            f'<p style="color:#7986CB; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.07em; margin:0;">{label}</p>'
            f'<p style="color:{color}; font-size:0.95rem; font-weight:600; margin:4px 0 0 0;">{status}</p>'
            f'<p style="color:#bbb; font-size:0.75rem; margin:2px 0 0 0;">{val:.1f}%</p>'
            f'</div>',
            unsafe_allow_html=True
        )

    st.markdown("")

    # ---- Tabs ----
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        t["tab_trends"], t["tab_costs"], t["tab_data"], t["tab_insights"], t["tab_about"]
    ])

    with tab1:
        st.markdown("")
        x_axis = m[month_col] if month_col else m.index

        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(
            x=x_axis, y=m[rev_col],
            name=t["revenue"],
            line=dict(color=INDIGO, width=2.5),
            mode='lines+markers',
            marker=dict(size=5)
        ))
        fig1.add_trace(go.Scatter(
            x=x_axis, y=m['Net_Profit'],
            name=t["net_profit"],
            line=dict(color='#2E7D32', width=2),
            mode='lines+markers',
            marker=dict(size=5),
            fill='tozeroy',
            fillcolor='rgba(46,125,50,0.06)'
        ))
        fig1.update_layout(
            title=dict(text=t["rev_vs_profit"], font=dict(size=14, color='#333')),
            plot_bgcolor='#ffffff',
            paper_bgcolor='#ffffff',
            font=dict(family='Inter', size=12, color='#666'),
            legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
            margin=dict(l=40, r=20, t=40, b=40),
            xaxis=dict(gridcolor='#f0f0f0', title=t["month"]),
            yaxis=dict(gridcolor='#f0f0f0', tickprefix='$', title=t["amount"]),
            height=380
        )
        st.plotly_chart(fig1, use_container_width=True)

        fig2 = go.Figure()
        fig2.add_trace(go.Bar(
            x=x_axis, y=m['Profit_Margin'],
            marker_color=[INDIGO if v > 0 else '#C62828' for v in m['Profit_Margin']],
            opacity=0.85
        ))
        fig2.update_layout(
            title=dict(text=t["monthly_margin"], font=dict(size=14, color='#333')),
            plot_bgcolor='#ffffff',
            paper_bgcolor='#ffffff',
            font=dict(family='Inter', size=12, color='#666'),
            margin=dict(l=40, r=20, t=40, b=40),
            xaxis=dict(gridcolor='#f0f0f0', title=t["month"]),
            yaxis=dict(gridcolor='#f0f0f0', ticksuffix='%', title=t["profit_margin_label"]),
            height=280,
            showlegend=False
        )
        st.plotly_chart(fig2, use_container_width=True)

    with tab2:
        st.markdown("")
        col_pie, col_table = st.columns([1, 1])

        with col_pie:
            labels = list(results['cost_breakdown'].keys())
            values = list(results['cost_breakdown'].values())
            colors = [INDIGO, '#5C6BC0', '#7986CB', '#9FA8DA', INDIGO_LIGHT, '#E8EAF6', '#F5F5F5']

            fig3 = go.Figure(data=[go.Pie(
                labels=labels,
                values=values,
                hole=0.55,
                marker=dict(colors=colors[:len(labels)]),
                textinfo='label+percent',
                textfont=dict(size=11, family='Inter'),
                hovertemplate='%{label}: $%{value:,.0f}<extra></extra>'
            )])
            fig3.update_layout(
                plot_bgcolor='#ffffff',
                paper_bgcolor='#ffffff',
                font=dict(family='Inter', size=12, color='#555'),
                margin=dict(l=10, r=10, t=10, b=10),
                height=360,
                showlegend=False
            )
            st.plotly_chart(fig3, use_container_width=True)

        with col_table:
            sorted_costs = sorted(results['cost_breakdown'].items(), key=lambda x: x[1], reverse=True)
            cost_df = pd.DataFrame(sorted_costs, columns=[t["category"], t["amount"]])
            cost_df[t["share"]] = (cost_df[t["amount"]] / cost_df[t["amount"]].sum() * 100).round(1)
            cost_df[t["amount"]] = cost_df[t["amount"]].apply(lambda x: f"${x:,.0f}")
            cost_df[t["share"]] = cost_df[t["share"]].apply(lambda x: f"{x}%")
            st.dataframe(cost_df, use_container_width=True, hide_index=True)

    with tab3:
        st.markdown("")
        display_cols = [c for c in m.columns if c not in ['Total_Expenses', 'Net_Profit', 'Profit_Margin']]
        display_df = m[display_cols].copy()
        st.dataframe(display_df, use_container_width=True, hide_index=True)

        output = BytesIO()
        m.to_excel(output, index=False)
        output.seek(0)
        dl_col1, dl_col2 = st.columns(2)
        with dl_col1:
            st.download_button(
                label=t["download"],
                data=output,
                file_name="abacus_report.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        with dl_col2:
            insights = generate_insights(results, t)
            pdf_buf = generate_pdf(results, t, insights)
            st.download_button(
                label=t["download_pdf"],
                data=pdf_buf,
                file_name="abacus_report.pdf",
                mime="application/pdf"
            )

    with tab4:
        st.markdown("")
        insights = generate_insights(results, t)

        for i, insight in enumerate(insights, 1):
            st.markdown(
                f'<div style="background:#ffffff; border-left:3px solid {INDIGO}; padding:14px 18px; margin-bottom:12px; border-radius:0 8px 8px 0; box-shadow:0 1px 3px rgba(63,81,181,0.04);">'
                f'<p style="color:#333; font-size:0.88rem; line-height:1.65; margin:0;">{insight}</p>'
                f'</div>',
                unsafe_allow_html=True
            )

        st.markdown("")
        st.markdown(
            f'<p style="color:#bbb; font-size:0.75rem;">'
            f'{t["insights_disclaimer"]}'
            f'</p>',
            unsafe_allow_html=True
        )

    with tab5:
        st.markdown("")

        # About page content
        st.markdown(
            f'<div style="max-width:640px;">'
            f'<h2 style="font-family:Source Serif 4,serif !important; font-size:1.6rem; color:#1a1a2e; margin-bottom:4px;">Abacus</h2>'
            f'<p style="color:#7986CB; font-size:0.9rem; margin-bottom:32px;">{t["tagline"]}</p>'
            f'</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            f'<div style="max-width:640px; margin-bottom:28px;">'
            f'<p style="color:{INDIGO}; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.1em; font-weight:600; margin-bottom:8px;">{t["about_problem_title"]}</p>'
            f'<p style="color:#444; font-size:0.92rem; line-height:1.75;">{t["about_problem"]}</p>'
            f'</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            f'<div style="max-width:640px; margin-bottom:28px;">'
            f'<p style="color:{INDIGO}; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.1em; font-weight:600; margin-bottom:8px;">{t["about_solution_title"]}</p>'
            f'<p style="color:#444; font-size:0.92rem; line-height:1.75;">{t["about_solution"]}</p>'
            f'</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            f'<div style="max-width:640px; margin-bottom:28px;">'
            f'<p style="color:{INDIGO}; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.1em; font-weight:600; margin-bottom:12px;">{t["about_principles_title"]}</p>'
            f'<div style="border-left:3px solid {INDIGO}; padding:12px 18px; margin-bottom:10px; background:#fafbff; border-radius:0 8px 8px 0;">'
            f'<p style="color:#333; font-size:0.88rem; line-height:1.65; margin:0;">{t["about_principle_1"]}</p>'
            f'</div>'
            f'<div style="border-left:3px solid #5C6BC0; padding:12px 18px; margin-bottom:10px; background:#fafbff; border-radius:0 8px 8px 0;">'
            f'<p style="color:#333; font-size:0.88rem; line-height:1.65; margin:0;">{t["about_principle_2"]}</p>'
            f'</div>'
            f'<div style="border-left:3px solid #7986CB; padding:12px 18px; margin-bottom:10px; background:#fafbff; border-radius:0 8px 8px 0;">'
            f'<p style="color:#333; font-size:0.88rem; line-height:1.65; margin:0;">{t["about_principle_3"]}</p>'
            f'</div>'
            f'</div>',
            unsafe_allow_html=True
        )

        st.markdown(
            f'<p style="color:#bbb; font-size:0.78rem; margin-top:32px;">{t["about_built"]}</p>',
            unsafe_allow_html=True
        )

    # ---- Summary Bar ----
    st.markdown("---")
    s1, s2, s3, s4 = st.columns(4)
    s1.markdown(
        f'<p style="color:#7986CB; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.07em;">{t["best_month"]}</p>'
        f'<p style="color:#1a1a2e; font-size:1rem; font-weight:600;">{results["best_month"]}</p>'
        f'<p style="color:#2E7D32; font-size:0.8rem;">${results["best_profit"]:,.0f} {t["profit_word"]}</p>',
        unsafe_allow_html=True
    )
    s2.markdown(
        f'<p style="color:#7986CB; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.07em;">{t["worst_month"]}</p>'
        f'<p style="color:#1a1a2e; font-size:1rem; font-weight:600;">{results["worst_month"]}</p>'
        f'<p style="color:#C62828; font-size:0.8rem;">${results["worst_profit"]:,.0f} {t["profit_word"]}</p>',
        unsafe_allow_html=True
    )
    s3.markdown(
        f'<p style="color:#7986CB; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.07em;">{t["avg_profit"]}</p>'
        f'<p style="color:#1a1a2e; font-size:1rem; font-weight:600;">${results["avg_monthly_profit"]:,.0f}</p>',
        unsafe_allow_html=True
    )
    s4.markdown(
        f'<p style="color:#7986CB; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.07em;">{t["gross_margin"]}</p>'
        f'<p style="color:#1a1a2e; font-size:1rem; font-weight:600;">{results["gross_margin"]:.1f}%</p>',
        unsafe_allow_html=True
    )

    st.markdown(
        f'<p class="footer-text">{t["footer"]}</p>',
        unsafe_allow_html=True
    )
